import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex items-center">
        <h1 className="text-h3 font-bold underline text-primary-main">
          Mustafa Salem
        </h1>
      </section>
    </>
  )
}
